### PR TITLE
This creates the marker component that will show up on the map. It is…

### PR DESCRIPTION
**Pull request by raustin9**
This creates the marker component that will show up on the map. It is currently unstyled. It only has the text 'sample text'. This will be grown later on once we make the map.

### CODE REVIEW

**Review by VishalAiely — APPROVED** [review]
Looks good to me so far!
The only comment I have is to maybe remove the import from './styles.scss' until we include that file.

**Comment by saithat** [comment]
looks good!

**Review by saithat — APPROVED** [review]
looks good!

**Review by braxtonhaynie — APPROVED** [review]
Looks good to me

**Pull request merged**
