### PR TITLE
H4ISH-9 text field and button

### PR DESCRIPTION
**Pull request by Riz-waan**

### CODE REVIEW

**Review by VishalAiely — CHANGES_REQUESTED** [review]
I think the code looks good but the formatting is off, to fix this run `yarn run eslint --fix src/components/SearchButton/index.tsx` from the root of the project and push that new commit up. That should fix the linter errors that showed up

**Comment by Riz-waan** [comment]
@VishalAiely Done.

**Review by VishalAiely — DISMISSED** [review]
Looks all good

**Review by VishalAiely — APPROVED** [review]

**Review by braxtonhaynie — APPROVED** [review]
Looks good to me

**Pull request merged**
